kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: default
  labels:
    io.kompose.service: nginx
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 31285
  selector:
    io.kompose.service: nginx
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
status:
  loadBalancer:
