---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  selector:
    app: nginx-example
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
