apiVersion: v1
kind: PersistentVolume
metadata:
  name: example
  labels:
    app: postgres
    type: local
spec:
  capacity:
    storage: 2Gi
  flexVolume:
    driver: ibm/ibmc-block
    fsType: ext4

  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  
  claimRef:
    kind: PersistentVolumeClaim
    namespace: myproject
    name: postgresql
  volumeMode: Filesystem  
  storageClassName: standard
