apiVersion: v1
kind: PersistentVolume
metadata:
  name: example
  labels:
    app: postgres
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/var/data"
