---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: mysite_3_web:v1.0.0
          imagePullPolicy: IfNotPresent 
          ports:
            - containerPort: 8001
      restartPolicy: Always
