apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
    name: nginx
spec:
  runPolicy: Serial
  source:
    dockerfile: |
      FROM centos:7
      RUN yum install -y epel-release && \
          yum install -y nginx

      COPY mysite_nginx.conf /etc/nginx/conf.d/

      COPY nginx.conf /etc/nginx/nginx.conf

      CMD ["nginx", "-g", "daemon off;", "-c", "/etc/nginx/nginx.conf"]

  strategy:
    type: Docker
    dockerStrategy:
      noCache: false
  output:
    to:
      kind: ImageStreamTag
      name: "nginx:latest"
