apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  ports:
  - name: nginx
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: nginx
  sessionAffinity: None
  type: ClusterIP
